In [160]:
# sample reader to read samples from /data/runs/samples
# and build each sample into a matrix

# Isaac Berez
# 14.01.23

from scipy.io import mmread
import os
import glob
import pandas as pd
import numpy as np
from pandas_ods_reader import read_ods
from copy import deepcopy
import pprint
import json

import sample_reader as sreader

# This notebook processes sample data related to sexual dimorphism research
## for reference, see 'Dimorph_samples.ods' file in /home/isaac/analysis/scRNA-seq

### 1) get sample ids and construct meta data from ods file

In [181]:
samples,meta_data_dict = sreader.process_meta_data(analysis_dir = '/home/isaac/analysis/scRNA-seq/',
                                dimorph_sample_file = 'Dimorph_samples.ods')
pprint.pprint(meta_data_dict)

{'10X35_1': {'Age': '8w',
             'Avesizebp_cDNAlib': nan,
             'Cell_Conc': 1000.0,
             'ChipID': '10X35',
             'Comments': 'Naive 8wo females, pooled, left hemisphere. 5%opti.',
             'Date': None,
             'Date_Captured': '2019-11-20',
             'DonorID': 'DI1,DI2',
             'Group': 'Naïve-F',
             'LIbConstructionComment': None,
             'Num_Pooled_Animals': 2.0,
             'PCR_Cycles': 13.0,
             'Project': 'Dimorph',
             'SampleID': '10X35_1',
             'Sample_Index': 'D9',
             'Serial_Number': 63.0,
             'Sex': 'F',
             'Species': 'Mm',
             'Strain': None,
             'Target_Num_Cells': 5000.0,
             'Tissue': 'MeA_L',
             'Transcriptome': 'Mm10',
             'cDNA_Lib_Ok': 'Y',
             'cDNAul': nan,
             'lengthbp_seqlib': 416.0,
             'ngperul_cDNA': 23.3,
             'ngperul_seqlib': 13.6},
 '10X35_2': {'Age': '8

In [179]:
pwd

'/data/runs/samples'

In [80]:
type(dimorph_df['Transcriptome:string'][0])

str

### 2. 

In [165]:

sample_dir = '/data/runs/samples/'
dimorph_samples = samples

os.chdir(sample_dir)
cwd = os.getcwd()
#print (cwd)

#for loop would go here to loop over samples
dir = str((glob.glob(cwd+'/'+dimorph_samples[0]+
                 '/'+'*out*'+'/'+'outs'+
                 '/'+'filtered_feature_bc_matrix'))).replace('[','').replace(']','')[1:-1]

#print(cwd)
#print (type(dir))
#print (os.listdir(dir))

m = mmread(dir + '/' + 'matrix.mtx')


In [166]:
m_arr = m.toarray()
print (m_arr)
print (m_arr.shape)
print (type(m_arr))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
(27998, 6229)
<class 'numpy.ndarray'>


In [167]:
barcodes = pd.read_csv(dir+'/'+'barcodes.tsv', sep='\t',header = None)
print(type(barcodes))
barcodes

<class 'pandas.core.frame.DataFrame'>


0
0     AAACCCACAACAGTGG-1
1     AAACCCACATGGCCCA-1
2     AAACCCAGTCCCTGAG-1
3     AAACGAACACTACAGT-1
4     AAACGAATCCCAGCGA-1
...                  ...
6224  TTTGGTTTCATCTGTT-1
6225  TTTGGTTTCTGTGCTC-1
6226  TTTGTTGAGATGTTCC-1
6227  TTTGTTGCATAGCACT-1
6228  TTTGTTGTCCGCGGAT-1

[6229 rows x 1 columns]

In [168]:
cells = barcodes.iloc[:,0]
cells.shape[0]

6229

In [169]:
dimorph_samples[0]

'10X54_1'

In [170]:
cells = barcodes.iloc[:,0] + dimorph_samples[0]
#print (type(cells))
cells = cells.values.reshape(cells.shape[0],1)
#cells = [cells + dimorph_samples[0] for x in cells]
print (cells)
print (cells.shape)
print (type(cells))

[['AAACCCACAACAGTGG-110X54_1']
 ['AAACCCACATGGCCCA-110X54_1']
 ['AAACCCAGTCCCTGAG-110X54_1']
 ...
 ['TTTGTTGAGATGTTCC-110X54_1']
 ['TTTGTTGCATAGCACT-110X54_1']
 ['TTTGTTGTCCGCGGAT-110X54_1']]
(6229, 1)
<class 'numpy.ndarray'>


In [171]:
features = pd.read_csv(dir+'/'+'features.tsv', sep='\t', header=None)
print(features)
print(features.iloc[0:4,1])

                        0               1                2
0      ENSMUSG00000051951            Xkr4  Gene Expression
1      ENSMUSG00000089699          Gm1992  Gene Expression
2      ENSMUSG00000102343         Gm37381  Gene Expression
3      ENSMUSG00000025900             Rp1  Gene Expression
4      ENSMUSG00000109048             Rp1  Gene Expression
...                   ...             ...              ...
27993  ENSMUSG00000079808      AC168977.1  Gene Expression
27994  ENSMUSG00000095041            PISD  Gene Expression
27995  ENSMUSG00000063897           DHRSX  Gene Expression
27996  ENSMUSG00000096730        Vmn2r122  Gene Expression
27997  ENSMUSG00000095742  CAAA01147332.1  Gene Expression

[27998 rows x 3 columns]
0       Xkr4
1     Gm1992
2    Gm37381
3        Rp1
Name: 1, dtype: object


In [172]:
gene_labels = features.iloc[:,1]
print (gene_labels)

gene_labels = gene_labels.values.reshape(gene_labels.shape[0],1)
#gene_labels = np.reshape(gene_labels ,(gene_labels.shape[0],1))
gene_labels.shape

0                  Xkr4
1                Gm1992
2               Gm37381
3                   Rp1
4                   Rp1
              ...      
27993        AC168977.1
27994              PISD
27995             DHRSX
27996          Vmn2r122
27997    CAAA01147332.1
Name: 1, Length: 27998, dtype: object


(27998, 1)

In [173]:
gene_labels

array([['Xkr4'],
       ['Gm1992'],
       ['Gm37381'],
       ...,
       ['DHRSX'],
       ['Vmn2r122'],
       ['CAAA01147332.1']], dtype=object)

In [174]:
#check for duplicates
print('unique values in gene labels: ', len(np.unique(gene_labels)))
print('total length gene labels: ', len(gene_labels))
print('# duplicates: ', len(gene_labels)-len(np.unique(gene_labels)))

unique values in gene labels:  27933
total length gene labels:  27998
# duplicates:  65


In [ ]:
#for duplicate 

In [128]:
len(cells)

6229

In [175]:
#combine into single dataframe
sample_df = pd.DataFrame(data = m_arr,
                         index = gene_labels,
                         columns = cells)
sample_df.iloc[:10,:4]

(AAACCCACAACAGTGG-110X54_1,)  (AAACCCACATGGCCCA-110X54_1,)  \
(Xkr4,)                                0                             0   
(Gm1992,)                              0                             0   
(Gm37381,)                             0                             0   
(Rp1,)                                 0                             0   
(Rp1,)                                 0                             0   
(Sox17,)                               0                             0   
(Gm37323,)                             0                             0   
(Mrpl15,)                              0                             0   
(Lypla1,)                              0                             0   
(Gm37988,)                             0                             0   

            (AAACCCAGTCCCTGAG-110X54_1,)  (AAACGAACACTACAGT-110X54_1,)  
(Xkr4,)                                0                             0  
(Gm1992,)                              0                             0  
(Gm37381,)                             0                             0  
(Rp1,)                                 0                             0  
(Rp1,)                                 0                             0  
(Sox17,)                               0                             0  
(Gm37323,)                             0                             0  
(Mrpl15,)                              1                             2  
(Lypla1,)                              0                             0  
(Gm37988,)                             0                             0

In [176]:
sample_df

(AAACCCACAACAGTGG-110X54_1,)  (AAACCCACATGGCCCA-110X54_1,)  \
(Xkr4,)                                       0                             0   
(Gm1992,)                                     0                             0   
(Gm37381,)                                    0                             0   
(Rp1,)                                        0                             0   
(Rp1,)                                        0                             0   
...                                         ...                           ...   
(AC168977.1,)                                 0                             0   
(PISD,)                                       0                             1   
(DHRSX,)                                      0                             0   
(Vmn2r122,)                                   0                             0   
(CAAA01147332.1,)                             0                             0   

                   (AAACCCAGTCCCTGAG-110X54_1,)  (AAACGAACACTACAGT-110X54_1,)  \
(Xkr4,)                                       0                             0   
(Gm1992,)                                     0                             0   
(Gm37381,)                                    0                             0   
(Rp1,)                                        0                             0   
(Rp1,)                                        0                             0   
...                                         ...                           ...   
(AC168977.1,)                                 0                             0   
(PISD,)                                       2                             0   
(DHRSX,)                                      0                             0   
(Vmn2r122,)                                   0                             0   
(CAAA01147332.1,)                             0                             0   

                   (AAACGAATCCCAGCGA-110X54_1,)  (AAACGAATCTGCTTAT-110X54_1,)  \
(Xkr4,)                                       0                             1   
(Gm1992,)                                     0                             0   
(Gm37381,)                                    0                             0   
(Rp1,)                                        0                             0   
(Rp1,)                                        0                             0   
...                                         ...                           ...   
(AC168977.1,)                                 0                             0   
(PISD,)                                       0                             1   
(DHRSX,)                                      0                             1   
(Vmn2r122,)                                   0                             0   
(CAAA01147332.1,)                             0                             0   

                   (AAACGCTAGCAGATAT-110X54_1,)  (AAACGCTAGTGCTCAT-110X54_1,)  \
(Xkr4,)                                       0                             0   
(Gm1992,)                                     0                             0   
(Gm37381,)                                    0                             0   
(Rp1,)                                        0                             0   
(Rp1,)                                        0                             0   
...                                         ...                           ...   
(AC168977.1,)                                 0                             0   
(PISD,)                                       0                             1   
(DHRSX,)                                      0                             0   
(Vmn2r122,)                                   0                             0   
(CAAA01147332.1,)                             0                             0   

                   (AAACGCTGTCCGTACG-110X54_1,)  (AAACGCTGTGGCTACC-110X54_1,)  \
(Xkr4,)                                       

In [177]:
#add duplicate rows together
sample_df_summed = sample_df.groupby(level=0).sum()
sample_df_summed

(AAACCCACAACAGTGG-110X54_1,)  (AAACCCACATGGCCCA-110X54_1,)  \
(0610007P14Rik,)                             0                             1   
(0610009B22Rik,)                             0                             0   
(0610009L18Rik,)                             0                             0   
(0610009O20Rik,)                             0                             0   
(0610010F05Rik,)                             0                             0   
...                                        ...                           ...   
(mt-Nd3,)                                    1                             9   
(mt-Nd4,)                                   10                            60   
(mt-Nd4l,)                                   0                             7   
(mt-Nd5,)                                    3                             7   
(mt-Nd6,)                                    0                             2   

                  (AAACCCAGTCCCTGAG-110X54_1,)  (AAACGAACACTACAGT-110X54_1,)  \
(0610007P14Rik,)                             5                             0   
(0610009B22Rik,)                             0                             1   
(0610009L18Rik,)                             0                             0   
(0610009O20Rik,)                             0                             0   
(0610010F05Rik,)                             0                             0   
...                                        ...                           ...   
(mt-Nd3,)                                   17                            21   
(mt-Nd4,)                                  117                            66   
(mt-Nd4l,)                                   8                             3   
(mt-Nd5,)                                   14                             8   
(mt-Nd6,)                                    1                             1   

                  (AAACGAATCCCAGCGA-110X54_1,)  (AAACGAATCTGCTTAT-110X54_1,)  \
(0610007P14Rik,)                             0                             0   
(0610009B22Rik,)                             0                             0   
(0610009L18Rik,)                             1                             0   
(0610009O20Rik,)                             0                             0   
(0610010F05Rik,)                             0                             0   
...                                        ...                           ...   
(mt-Nd3,)                                    9                             6   
(mt-Nd4,)                                   30                            50   
(mt-Nd4l,)                                   4                             3   
(mt-Nd5,)                                    5                             5   
(mt-Nd6,)                                    0                             0   

                  (AAACGCTAGCAGATAT-110X54_1,)  (AAACGCTAGTGCTCAT-110X54_1,)  \
(0610007P14Rik,)                             1                             0   
(0610009B22Rik,)                             0                             0   
(0610009L18Rik,)                             0                             0   
(0610009O20Rik,)                             0                             0   
(0610010F05Rik,)                             0                             0   
...                                        ...                           ...   
(mt-Nd3,)                                   14                            23   
(mt-Nd4,)                                   87                           144   
(mt-Nd4l,)                                   1                             5   
(mt-Nd5,)                                    7                            19   
(mt-Nd6,)                                    0                             0   

                  (AAACGCTGTCCGTACG-110X54_1,)  (AAACGCTGTGGCTACC-110X54_1,)  \
(0610007P14Rik,)                             2                             1   
(0610009B22Rik